#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export CLICOLOR=1
export HISTCONTROL=erasedups
export JAVA_HOME=`/usr/libexec/java_home`
export GROOVY_HOME=/usr/local/Cellar/groovy/Current/libexec
export GOPATH=$HOME
export PATH=$PATH:/usr/local/lib/oracle:$GOPATH/bin
alias protoc-2.5=protoc
alias k=kubectl
